CREATE TABLE IF NOT EXISTS public.recipe
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    amount real,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT recipe_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recipe
    OWNER to coffee_user;




CREATE TABLE IF NOT EXISTS public.coffee
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    price real,
    CONSTRAINT coffee_pkey PRIMARY KEY (id),
    CONSTRAINT ukhxgkcjhh5fkfkf3t119jswrbw UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.coffee
    OWNER to coffee_user;

CREATE TABLE IF NOT EXISTS public.coffee_recipes
(
    coffee_id integer NOT NULL,
    recipes_id integer NOT NULL,
    CONSTRAINT uk7ts2vkb7svoxugk1uwcmp7n60 UNIQUE (recipes_id),
    CONSTRAINT fk9gp7imvnqe39nyyhew3jbrt8b FOREIGN KEY (coffee_id)
        REFERENCES public.coffee (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkcyf8mnd023pg187xenqy7u1xe FOREIGN KEY (recipes_id)
        REFERENCES public.recipe (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.coffee_recipes
    OWNER to coffee_user;


CREATE TABLE IF NOT EXISTS public.ingredients
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    amount real,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT ingredients_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.ingredients
    OWNER to coffee_user;


CREATE TABLE IF NOT EXISTS public.orders
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    coffee_name character varying(255) COLLATE pg_catalog."default",
    created_at date,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.orders
    OWNER to coffee_user;



